### ISSUE TITLE
Support field-based throttling in alerts

### ISSUE THREAD

**Issue by bcanvural** [clearhaus/terraform-provider-humio#2]
Dear maintainers,

First off, thank you so much for forking and uploading this provider to terraform registry! At Bloomreach we were thinking of using this to manage some humio alerts and potentially other suff. However we noticed that unfortunately currently one little feature is not supported: field-based throttling in the humio alerts. It looks pretty simple to implement as it's just another field in alerts it looks like. Thoughts? Would you want to look into it, or if I wanted to do it would you merge and make another release in terraform registry? 
Thank you so much for your time!

**Comment by kbadk** [comment]
Hi there!

First off: I apologize for the slow response – this issue just slipped my mind.

This was actually already implemented in July, but I now notice that it never made it into this fork. See https://github.com/humio/terraform-provider-humio/pull/23. This also lead me to discover that https://github.com/humio/terraform-provider-humio/pull/21 and https://github.com/humio/terraform-provider-humio/pull/22 also had been left behind, so thank you!

I've just added the above PRs in https://github.com/clearhaus/terraform-provider-humio/commit/4957a60e3b80f38ac56189d15c6f8566f346cc0c, https://github.com/clearhaus/terraform-provider-humio/commit/e5be55944b0c902e2cc9b59114bdd8ad48457253 and https://github.com/clearhaus/terraform-provider-humio/commit/a164906f0ad6cc7b64e285c66d0ac195f1386d1d, respectively, and [released a v0.3.0](https://registry.terraform.io/providers/clearhaus/humio/0.3.0): 

To answer your question – if you in the future would like to contribute, we're more than happy to receive minors PRs and publish new changes!

**Comment by bcanvural** [comment]
Hi @kbadk , thanks for getting back to my message!

Nice! Happy to hear that these were already implemented! I checked the newly released terraform provider and indeed the field based throttling in alerts work. I'll close the issue.
You have  a great day!
