### ISSUE TITLE
Support runAsUserId to allow alerts to be run as the organization

### ISSUE THREAD

**Issue by MLSLasecki** [clearhaus/terraform-provider-humio#9]
Hello maintainers,

I've been looking into this provider and it seems to be the perfect solution for managing alerts/parser with code and version control, so thank you a lot for maintaining this project.

Lately LogScale added a feature to alerts that allows them to be run as the org instead of a specific user. This is important for production alerts, because if they are assigned to a user and that user is removed the the query stops running.

Would it be possible to add this functionality to the provider?
As far as I can see, this might require setting Alert.RunAsUserID to nil (alerts run as the org have 'null' in the GraphQL field runAsUser.id), and potentially also doing something with QueryOwnershipType (in GraphQL I can see that only alerts running as the org have a value in queryOwnership.id and it's always set to SINGLE_ORGANIZATION_ID, but it might be different in the cloud)

Once again, thanks so much for your work!

**Comment by kbadk** [comment]
Hi there,

I've implemented support for the new fields in https://github.com/clearhaus/terraform-provider-humio/pull/10. I'd appreciate if you could check it out before I publish it as a new version. There are instructions on how to run and build the provider in the README.

For the record, we're always open to PRs, so if you find yourself needing a new feature in the future, go ahead and take a stab at it yourself. I can't guarantee that we'll prioritize features we don't need ourselves, but luckily this was fairly simple to implement.

**Comment by MLSLasecki** [comment]
Hi again,

I played around with the new parameter and it works like a charm.
Thank a lot for such a quick response.

I've dug through the code a bit while testing so I should be able to make pull requests instead of issues going forward (already have some ideas there).

**Comment by kbadk** [comment]
That's great to hear! v0.6.0 has just been published at https://registry.terraform.io/providers/clearhaus/humio/0.6.0.
